from flask import Flask, request, render_template_string
import pandas as pd
import io  # Needed for StringIO - used to make a file-like object in memory

# ALL HTML TEMPLATES IN THIS DOCUMENT WAS GENERATED BY CHATGPT

# Base template - includes code for flashed messsages and the "refresh 
# sessipon" button
UPLOAD_PAGE = """
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

<form action='/refresh' method='post' style='margin-bottom: 1rem;'>
    <button type='submit'>Refresh session</button>
</form>
"""

# The whole template for the home upload screen. Includes buttons to browse
# and upload fines. Another button starts the validation and annotation 
# modules.
UPLOAD_TEMPLATE = UPLOAD_PAGE + """
        <h1>Welcome to ParkVar!</h1>
        <h3>Upload files</h3>

        <form method='POST' enctype='multipart/form-data'>
            <input type='file' name='file' accept='.csv' required>
            <button type='submit'>Upload</button>
        </form>
        """

UPLOAD_ANNO_TEMPLATE = UPLOAD_TEMPLATE + """
        {% if table_html %}
            <hr>
            <div>
              {{ table_html|safe }}
            </div>
        {% endif %}

        <h3>Upload more files or annotate your data</h3>
        <form action='/annotate' method='post'>
        <button type='submit' id='annotate-btn'>Annotate</button>
        </form>

        <p id='annotating-msg' style='display:none; color: red; margin-top:1rem;'>
        Annotating variants, this may take a few seconds...
        </p>

        <script>
        document.addEventListener('DOMContentLoaded', function () {
            const btn = document.getElementById('annotate-btn');
            const msg = document.getElementById('annotating-msg');

            if (btn) {
                btn.addEventListener('click', function () {
                    msg.style.display = 'block';
                });
            }
        });
        </script>

        <h3>Uploaded data</h3>
"""

ANNO_TEMPLATE = UPLOAD_PAGE + '''
        <p><em>{{ applied_text }}</em></p>

        <h3>Filter by Patient_ID</h3>
        <form action='/filter' method='post' style='margin-bottom: 1rem;'>
            {% for pid in patient_ids %}
                <label>
                    <input type='checkbox'
                           name='patient_id'
                           value='{{ pid }}'
                           {% if pid in selected_ids %}checked{% endif %}>
                    {{ pid }}
                </label><br>
            {% endfor %}
            <button type='submit' style='margin-top: 1rem;'>Apply filter</button>
        </form>

        <hr>
        <h2>Filtered data</h2>
        {{ table|safe }}
        '''

def create_df(file):
    # Read the raw bytes from the file object (that is encoded in UTF-8)
    text = file.read().decode("utf-8")
    # Read file into a pandas data frame
    # io.StringIO - pandas usually expects a file on disk. When a file is
    # read using a form, it is only raw bytes in memory. StringIO creates
    # an in-memory file-object that acts like a normal file
    df = pd.read_csv(io.StringIO(text))
    return df


def create_table(df):
    table = render_template_string(
        # Template for table
        "<h3></h3><p>Rows: {{ n }}</p>{{ table|safe }}<hr>",
        n=len(df),  # Number of rows
        # Convert the pandas dataframe into simple HTML table
        table=df.to_html(index=False),  # index=False - remove the index column
    )
    return table


def load_uploaded_filenames(uploaded_files):
    if not uploaded_files.exists():
        return list()
    return [
        line.strip()
        for line in uploaded_files.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def save_uploaded_filenames(uploaded_files, filenames: list):
    uploaded_files.write_text("\n".join(sorted(filenames)), encoding="utf-8")

def show_checkboxes(table_html, patient_ids, selected_ids=None):
    selected_ids = set(selected_ids or [])

    return render_template_string(
        UPLOAD_PAGE + '''
        <h3>Filter by Patient_ID</h3>
        <form action='/filter' method='post' style='margin-top: 1rem;'>
          {% for pid in patient_ids %}
            <label>
              <input type='checkbox'
                     name='patient_id'
                     value='{{ pid }}'
                     {% if pid in selected_ids %}checked{% endif %}>
              {{ pid }}
            </label><br>
          {% endfor %}
          <button type='submit' style='margin-top: 1rem;'>Apply filter</button>
        </form>

        <hr>
        <h2>Annotated data</h2>
        {{ table|safe }}

        ''',
        table=table_html,
        patient_ids=patient_ids,
        selected_ids=selected_ids,
        show_upload=False   # hide the upload UI on this page
    )